name: Branches CI

on:
  # Trigger the workflow on push
  # but only for the non master branches
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        jdk: [ 1.8, 11 ]
        os: [ windows-latest, ubuntu-latest, macos-latest, ubuntu-20.04 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: eskatos/gradle-command-action@v1
        name: Build with Gradle
        with:
          arguments: clean build --info
      - name: Publish Packages to Artifactory
        if: ${{ matrix.jdk == '1.8' }}
        run: ./gradlew -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" -PversionSuffix="-${githubRef#refs/heads/}-SNAPSHOT" -PbuildNumber="${buildNumber}" artifactoryPublish --stacktrace
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayKey: ${{ secrets.bintrayKey }}
          githubRef: ${{ github.ref }}
          buildNumber: ${{ github.run_number }}
